[configurer]
release_from_tar = false
release_dir = "."
roots_dir = "."



[specs]
release = "CMSSW_14_1_0_pre4"
type = "close_by_particle_gun"
era = 2026
pileup = false
geometry = "D110"
#process_modifier = "ticl_v3"

[workflow]
customize_step3 = false
num_events = 1000
step = 3

[generator]
verbosity = 0
first_run = 1
psethack = "random particles in phi and r windows"


[generator.parameters]
# particle_ids = [["PROTON", "GAMMA"], ["ELECTRON", "PROTON"]]
delta = [4, 5]
# flat_pt_generation = [false, true]
# eta = [[1.0, 2.0], [2 , 4] , [4, 6]]


